"""add_email_to_users

Revision ID: 3d1c19bb0a88
Revises: dbe3eaf1b4b8
Create Date: 2026-07-10 03:28:57.952935
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "3d1c19bb0a88"
down_revision: Union[str, None] = "dbe3eaf1b4b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "users", ["email"])

    op.execute("""
        UPDATE users
        SET email = username || '@example.com'
        WHERE email IS NULL
    """)

    op.alter_column(
        "users", "email", existing_type=sa.String(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
