"""add display_name to users

Revision ID: dbe3eaf1b4b8
Revises: a2b3c4d5e6f7
Create Date: 2026-07-09 01:30:20.912156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbe3eaf1b4b8'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
