"""add letroso tables

Revision ID: eca2c4ce5d43
Revises: dbe3eaf1b4b8
Create Date: 2026-07-10 01:42:10.145144
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eca2c4ce5d43'
down_revision: Union[str, None] = 'e4d5c6b7a8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letroso_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=10), nullable=False),
    sa.Column('word_length', sa.Integer(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letroso_words_word'), 'letroso_words', ['word'], unique=True)
    op.create_table('letroso_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('played_date', sa.Date(), nullable=False),
    sa.Column('word_length', sa.Integer(), nullable=False),
    sa.Column('guesses', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('solved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'played_date', name='uq_user_letroso_date')
    )
    op.create_index(op.f('ix_letroso_sessions_played_date'), 'letroso_sessions', ['played_date'], unique=False)
    op.create_index(op.f('ix_letroso_sessions_user_id'), 'letroso_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letroso_sessions_user_id'), table_name='letroso_sessions')
    op.drop_index(op.f('ix_letroso_sessions_played_date'), table_name='letroso_sessions')
    op.drop_table('letroso_sessions')
    op.drop_index(op.f('ix_letroso_words_word'), table_name='letroso_words')
    op.drop_table('letroso_words')
    # ### end Alembic commands ###
